//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class BattleConfig :  Bright.Config.BeanBase 
{
    public BattleConfig(ByteBuf _buf) 
    {
        PlayerMaxHp = _buf.ReadInt();
        PostInit();
    }

    public static BattleConfig DeserializeBattleConfig(ByteBuf _buf)
    {
        return new BattleConfig(_buf);
    }

    /// <summary>
    /// 玩家最大血量（开局）
    /// </summary>
    public int PlayerMaxHp { get; private set; }

    public const int __ID__ = 1899407930;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PlayerMaxHp:" + PlayerMaxHp + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}