//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
/// <summary>
/// 标靶定义
/// </summary>
public sealed partial class Brick :  Bright.Config.BeanBase 
{
    public Brick(ByteBuf _buf) 
    {
        BrickID = _buf.ReadString();
        HPMin = _buf.ReadInt();
        HPMax = _buf.ReadInt();
        Weight = _buf.ReadInt();
        PostInit();
    }

    public static Brick DeserializeBrick(ByteBuf _buf)
    {
        return new Brick(_buf);
    }

    /// <summary>
    /// 标靶ID
    /// </summary>
    public string BrickID { get; private set; }
    /// <summary>
    /// 最小生命值
    /// </summary>
    public int HPMin { get; private set; }
    /// <summary>
    /// 最大生命值
    /// </summary>
    public int HPMax { get; private set; }
    /// <summary>
    /// 概率
    /// </summary>
    public int Weight { get; private set; }

    public const int __ID__ = 64452641;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "BrickID:" + BrickID + ","
        + "HPMin:" + HPMin + ","
        + "HPMax:" + HPMax + ","
        + "Weight:" + Weight + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}