//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class BrickPool :  Bright.Config.BeanBase 
{
    public BrickPool(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);BrickConfig = new System.Collections.Generic.List<Brick>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Brick _e0;  _e0 = Brick.DeserializeBrick(_buf); BrickConfig.Add(_e0);}}
        PostInit();
    }

    public static BrickPool DeserializeBrickPool(ByteBuf _buf)
    {
        return new BrickPool(_buf);
    }

    /// <summary>
    /// 标靶池配置表
    /// </summary>
    public int ID { get; private set; }
    public System.Collections.Generic.List<Brick> BrickConfig { get; private set; }

    public const int __ID__ = -581792803;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in BrickConfig) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in BrickConfig) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BrickConfig:" + Bright.Common.StringUtil.CollectionToString(BrickConfig) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}