//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg
{ 
    public enum MarbleReward
    {
        /// <summary>
        /// 士兵
        /// </summary>
        Soldier = 0,
        /// <summary>
        /// 加血
        /// </summary>
        HPRecover = 1,
    }

} 
