//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class MonsterPool :  Bright.Config.BeanBase 
{
    public MonsterPool(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Monster = new System.Collections.Generic.List<MonsterRefreshConfig>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { MonsterRefreshConfig _e0;  _e0 = MonsterRefreshConfig.DeserializeMonsterRefreshConfig(_buf); Monster.Add(_e0);}}
        PostInit();
    }

    public static MonsterPool DeserializeMonsterPool(ByteBuf _buf)
    {
        return new MonsterPool(_buf);
    }

    /// <summary>
    /// 怪物概率池
    /// </summary>
    public int ID { get; private set; }
    public System.Collections.Generic.List<MonsterRefreshConfig> Monster { get; private set; }

    public const int __ID__ = -1085702410;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var _e in Monster) { _e?.Resolve(_tables); }
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var _e in Monster) { _e?.TranslateText(translator); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Monster:" + Bright.Common.StringUtil.CollectionToString(Monster) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}