//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
public sealed partial class SoldierConfig :  Bright.Config.BeanBase 
{
    public SoldierConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadString();
        Hp = _buf.ReadInt();
        Type = _buf.ReadFloat();
        MaxLifePoint = _buf.ReadInt();
        Damage = _buf.ReadInt();
        Resource = _buf.ReadString();
        PostInit();
    }

    public static SoldierConfig DeserializeSoldierConfig(ByteBuf _buf)
    {
        return new SoldierConfig(_buf);
    }

    /// <summary>
    /// 士兵配置表，由标靶表外键引用。
    /// </summary>
    public string Id { get; private set; }
    public int Hp { get; private set; }
    public float Type { get; private set; }
    public int MaxLifePoint { get; private set; }
    public int Damage { get; private set; }
    public string Resource { get; private set; }

    public const int __ID__ = -1161791676;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Hp:" + Hp + ","
        + "Type:" + Type + ","
        + "MaxLifePoint:" + MaxLifePoint + ","
        + "Damage:" + Damage + ","
        + "Resource:" + Resource + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}