//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace cfg
{ 
public partial class Tables
{
    public TbLevelConfig TbLevelConfig {get; }
    public TbBrickConfig TbBrickConfig {get; }
    public TbBrickPool TbBrickPool {get; }
    public TbMonsterConfig TbMonsterConfig {get; }
    public TbMonsterPool TbMonsterPool {get; }
    public TbGlobalConfig TbGlobalConfig {get; }
    public TbSoldierConfig TbSoldierConfig {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbLevelConfig = new TbLevelConfig(loader("tblevelconfig")); 
        tables.Add("TbLevelConfig", TbLevelConfig);
        TbBrickConfig = new TbBrickConfig(loader("tbbrickconfig")); 
        tables.Add("TbBrickConfig", TbBrickConfig);
        TbBrickPool = new TbBrickPool(loader("tbbrickpool")); 
        tables.Add("TbBrickPool", TbBrickPool);
        TbMonsterConfig = new TbMonsterConfig(loader("tbmonsterconfig")); 
        tables.Add("TbMonsterConfig", TbMonsterConfig);
        TbMonsterPool = new TbMonsterPool(loader("tbmonsterpool")); 
        tables.Add("TbMonsterPool", TbMonsterPool);
        TbGlobalConfig = new TbGlobalConfig(loader("tbglobalconfig")); 
        tables.Add("TbGlobalConfig", TbGlobalConfig);
        TbSoldierConfig = new TbSoldierConfig(loader("tbsoldierconfig")); 
        tables.Add("TbSoldierConfig", TbSoldierConfig);

        PostInit();
        TbLevelConfig.Resolve(tables); 
        TbBrickConfig.Resolve(tables); 
        TbBrickPool.Resolve(tables); 
        TbMonsterConfig.Resolve(tables); 
        TbMonsterPool.Resolve(tables); 
        TbGlobalConfig.Resolve(tables); 
        TbSoldierConfig.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbLevelConfig.TranslateText(translator); 
        TbBrickConfig.TranslateText(translator); 
        TbBrickPool.TranslateText(translator); 
        TbMonsterConfig.TranslateText(translator); 
        TbMonsterPool.TranslateText(translator); 
        TbGlobalConfig.TranslateText(translator); 
        TbSoldierConfig.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}