//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbBrickPool
{
    private readonly Dictionary<int, BrickPool> _dataMap;
    private readonly List<BrickPool> _dataList;
    
    public TbBrickPool(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, BrickPool>();
        _dataList = new List<BrickPool>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            BrickPool _v;
            _v = BrickPool.DeserializeBrickPool(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, BrickPool> DataMap => _dataMap;
    public List<BrickPool> DataList => _dataList;

    public BrickPool GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BrickPool Get(int key) => _dataMap[key];
    public BrickPool this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}