//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbLevelConfig
{
    private readonly List<LevelConfig> _dataList;

    private Dictionary<(int, int), LevelConfig> _dataMapUnion;

    public TbLevelConfig(ByteBuf _buf)
    {
        _dataList = new List<LevelConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            LevelConfig _v;
            _v = LevelConfig.DeserializeLevelConfig(_buf);
            _dataList.Add(_v);
        }
        _dataMapUnion = new Dictionary<(int, int), LevelConfig>();
        foreach(var _v in _dataList)
        {
            _dataMapUnion.Add((_v.LevelID, _v.StageID), _v);
        }
        PostInit();
    }


    public List<LevelConfig> DataList => _dataList;

    public LevelConfig Get(int LevelID, int StageID) => _dataMapUnion.TryGetValue((LevelID, StageID), out LevelConfig __v) ? __v : null;

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}