//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg
{
   
public partial class TbSoldierConfig
{
    private readonly Dictionary<string, SoldierConfig> _dataMap;
    private readonly List<SoldierConfig> _dataList;
    
    public TbSoldierConfig(ByteBuf _buf)
    {
        _dataMap = new Dictionary<string, SoldierConfig>();
        _dataList = new List<SoldierConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SoldierConfig _v;
            _v = SoldierConfig.DeserializeSoldierConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<string, SoldierConfig> DataMap => _dataMap;
    public List<SoldierConfig> DataList => _dataList;

    public SoldierConfig GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SoldierConfig Get(string key) => _dataMap[key];
    public SoldierConfig this[string key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}